(in-package :one-more-re-nightmare)

(defun derivative (re set)
  (trivia:ematch re
    ((empty-string) (empty-set))
    ((literal matching-set)
     (if (set-null (set-intersection matching-set set))
         (empty-set)
         (empty-string)))
    ((join r s)
     (if (nullable r)
         (either (join (derivative r set)
                       s)
                 (derivative s set))
         (join (derivative r set)
               s)))
    ((kleene r)
     (join (derivative r set) (kleene r)))
    ((either r s)
     (either (derivative r set)
             (derivative s set)))
    ((both r s)
     (both (derivative r set)
           (derivative s set)))
    ((invert r) (invert (derivative r set)))))
