(in-package :one-more-re-nightmare)

(trivia:defun-match has-literals-p (re)
  ((literal _) t)
  ((either r s)
   (and (has-literals-p r) (has-literals-p s)))
  ((or (join r s) (both r s))
   (or (has-literals-p r) (has-literals-p s)))
  ((invert r) (not (has-literals-p r)))
  (_ nil))

(trivia:defun-match effects (re)
  ((tag-set s) s)
  ((join r s)
   (if (has-literals-p r)
       (effects r)
       (union (effects r) (effects s)
              :test #'equal)))
  ((or (either r s) (both r s))
   (union (effects r) (effects s)
          :test #'equal))
  ((invert r) (effects r))
  ((kleene r) (effects r))
  ((alpha e _) (effects e))
  ((grep v _) (effects v))
  (_ '()))
